server:
  port: 8080

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=0

        - id: upload-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/upload/**
          filters:
            - StripPrefix=0

        - id: product-ai-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - StripPrefix=0

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=0

        - id: cart-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - StripPrefix=0
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

logging:
  charset:
    console: UTF-8
    file: UTF-8

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
